# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'UITools' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
   pod 'SDWebImage', '~>3.7'
  # Pods for UITools

end


